-- ==============================================================
-- BẢNG DANH MỤC NHÀ CUNG CẤP (nha_cung_cap)
-- Seed 141 NCC từ file "danh mục nhà cung cấp.xlsx" (đã khử 4 mã trùng)
-- Chạy lại nhiều lần an toàn nhờ ON CONFLICT (ma_ncc) DO NOTHING.
-- ==============================================================

CREATE TABLE IF NOT EXISTS public.nha_cung_cap (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ma_ncc        TEXT NOT NULL UNIQUE,     -- Mã NCC (VD: AIRMEC)
  ten_ncc       TEXT,                     -- Tên NCC
  nguoi_lien_he TEXT,                     -- Người liên hệ
  so_dien_thoai TEXT,                     -- SĐT — TEXT để giữ số 0 đầu / khoảng trắng
  dia_chi       TEXT,                     -- Địa chỉ
  ghi_chu       TEXT,                     -- Ghi chú
  created_at    TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL,
  updated_at    TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ncc_ten ON public.nha_cung_cap (ten_ncc);

-- RLS: cho phép truy cập toàn quyền (đồng bộ các bảng kho khác — app dùng anon key + kiểm quyền phía client)
ALTER TABLE public.nha_cung_cap ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable full access for all users" ON public.nha_cung_cap;
CREATE POLICY "Enable full access for all users" ON public.nha_cung_cap FOR ALL USING (true);

-- Seed dữ liệu
INSERT INTO public.nha_cung_cap (ma_ncc, ten_ncc, nguoi_lien_he, so_dien_thoai, dia_chi) VALUES
  ('AIRMEC', 'Công ty TNHH cơ khí Airmec', 'MR HHH', '983921546', 'Tân Quang, Văn Lâm, Hưng Yên'),
  ('ANHBAO', 'ANH BẢO', 'HCM', NULL, NULL),
  ('ANHLAM', 'Công ty TNHH đầu tư thương mại Anh Lâm', 'Mr Trung', '912124008', 'Số 69 A, Phố Đại Từ , Hoàng Mai, HN'),
  ('ANHQUANG', 'ANH QUANG', NULL, '8888981111', 'Chung cư TNR Goldmark 136 Hồ Tùng mậu'),
  ('ANHSOAI', 'Anh Soái', 'Anh Soái', '096 6386868', NULL),
  ('ANTHY', 'Công ty TNHH công nghệ môi trường An Thy', 'Ms Thảo', '2432018585', 'Trâu Quỳ, Gia Lâm, HN'),
  ('AVICOM', 'CÔNG TY TNHH QUẢNG CÁO VÀ TRUYỀN THÔNG AVICOM', 'THÔNG AVICOM', '0989927266', '0989927266'),
  ('AVINA', 'CÔNG TY CP ĐẦU TƯ & GIẢI PHÁP AVINA', NULL, NULL, 'CHÂU QUỲ, GIA LÂM'),
  ('BLKCS2', 'Bán linh kiện.com', NULL, '986816352', 'Số 2-132/86 Nguyên Xá, Bắc Từ Liêm, HN'),
  ('CANG', 'ANH HẢI', 'ANH HẢI', '0961150379', '0961150379'),
  ('CAONGUYEN', 'fLOWAVE CO.,LTD', NULL, NULL, NULL),
  ('CHESTERPAUL', 'Chester Paul Company', NULL, NULL, NULL),
  ('CHICO', 'Công ty tnhh thượng mại Chico', 'Mr', '824184444', 'Số 2 Lương Ngọc Quyến, P Văn Quán, Q Hà Đông, Hà Nội'),
  ('CLAIRE', 'CLAIRE TECHNOLOGIES MANUFACTURING, INC', 'CLAIRE TECHN', '0989927267', '0989927267'),
  ('CLARIER', 'Clarier', 'Clarier', '392581335', 'Canada'),
  ('CNHANOI', 'Công ty TNHH thiết bị công nghiệp Hà nội', 'Ms Hoa', '961865247', 'Ngọc Hồi,Thanh Trì, Hà Nội'),
  ('CTYPMNHANHOA', 'Công ty TNHH phần mềm Nhân Hòa', 'mềm Nhân Hòa', '0989927268', '0989927268'),
  ('CUONGTHINH', 'Công ty TNHH Sản xuất và thương mại Cường Thịnh', NULL, '914301819', 'KĐT Đại Kim, Hoàng Mai, HN'),
  ('DAC', 'Công ty TNH H công nghệ chống giả DAC', 'Ms Hương', '984323773', '72 Trường Chinh, P Phương Mai, Q Đống Đa, HN'),
  ('DAMHUONG', 'Công ty TNHH TM&DV Đảm Hương', 'Mr Hương', '982209976', 'Văn Giang, Hưng Yên'),
  ('DANDAT', 'Công ty Dân Đạt', NULL, NULL, NULL),
  ('DGTK', 'Đóng gói tiết kiệm', NULL, NULL, NULL),
  ('DOANKET', 'Công ty TNHH TM và SX bao bì Đoàn Kết', NULL, NULL, 'Cụm công nghiệp An Khánh-KM8 Đại lộ Thăng Long'),
  ('DONGHAN', 'Công ty TNHH sản xuất TM&DV Đông Hân', 'MS Thảo', '793188805', 'Lô 24 Cụm CN Yên Nghĩa, Hà Đông, Hà Nội'),
  ('DORRY', 'DORRY', NULL, NULL, NULL),
  ('DTMB', 'Công ty tnhh thiết bị môi trường đô thị Miền Bắc', 'Mr Việt', '966891586', 'Yên Nghĩa, Hà Đông'),
  ('DUBIC', 'Dubic Electric', 'Mr Nam', '333308526', 'Trần Khát Chân, P Thanh Lương, Hai Bà Trưng, Hn'),
  ('DUCDUONG', 'Đức Dương', 'MR Dương', '392581335', 'HN'),
  ('DUCHUAN', 'Bao bì Đức Huân', 'bì Đức Huân', '0862353168', NULL),
  ('DUCLOC', 'Công ty TNHH quảng cáo và in ấn Đức Lộc', 'Mr Lộc', '948403258', 'Phú ĐÔ, NTL, HN'),
  ('DUCTUAN', 'CÔNG TY TNHH ĐẦU TƯ VÀ SX BAO BÌ ĐỨC TUẤN', 'DUC TUAN', '862353168', 'NGUYỄN XÁ 3, MIN KHAI, BẮC TỪ LIÊM, HÀ NỘI'),
  ('DUNGTHOA', 'Dũng Thoa', 'Dũng Thoa', '911556898', 'Thạch Thất, Hà Nội'),
  ('DUNGYEN', 'Công ty TNHH DV và TM Dũng Yến', NULL, '904766903', NULL),
  ('DUONG DONG', 'Dương Đông', 'Ms Thành', '868802858', 'Phương Canh Nam Từ Liêm Hà Nội'),
  ('DUONGSANG', 'Công ty tnhh kim khí Đường Sáng', 'í Đường Sáng', '918361998', '918361998'),
  ('ETA', 'CÔNG TY TNHH THƯƠNG MẠI XUẤT NHẬP KHẨU E - TA VIỆT NAM', 'TA VIỆT NAM', '0989927269', '0989927269'),
  ('FLOWAVE', 'fLOWAVE CO.,LTD', 'Mr Hà', '392581335', 'Đài Loan'),
  ('FLOWAVE CO.,LTD', 'FLOWAVE CO.,LTD', 'Ms Hà', '392581335', 'Hàn Quốc'),
  ('GE', 'Công ty TNHH kỹ thuật GE', 'Ms Yến', '965769955', 'Mỹ Đình 1, Nam Từ Liêm, HN'),
  ('GHTK', 'Giao hàng tiết kiệm', NULL, NULL, NULL),
  ('GNB', 'GNB Korea', NULL, NULL, NULL),
  ('HABACH', 'Công ty TNHH thương mại và đầu tư phát triển Hà Bách', 'Mr Bách', '832233588', 'Văn Quán, Hà Đông'),
  ('HAICHIN', 'KIM KHÍ HẢI CHÍN', NULL, '989452252', 'SỐ 153 ĐƯỜNG 70'),
  ('HAINAM', 'Công ty TNHH nhựa quốc tế Hải Nam', NULL, NULL, NULL),
  ('HAIYEN', 'Lọc nước Hải Yến', 'nước Hải Yến', '918810110', '918810110'),
  ('HAOTUYEN', 'CỬA HÀNG HẢO TUYÊN', 'ANH HẢO', '912347679', 'MIÊU NHA'),
  ('HATHU', 'CÔNG TY TNHH SẢN XUẤT VÀ KINH DOANH HÀ THƯ', 'DOANH HÀ THƯ', '0989927271', '0989927271'),
  ('HBTECH', 'HB TECH CO.,LTD', 'HB TECH CO.,', '0989927272', '0989927272'),
  ('HC', 'Công ty CP quà tặng HC', 'Phạm Thanh Thuỷ', '964160066', 'Cụm 3 thôn Hạ Hội, xã Tân Lập , huyện Đan Phượng, Hà Nội'),
  ('HCM', 'Kho HCM', NULL, NULL, 'Kho HCM'),
  ('HIEUNHUNG', 'ĐIỆN CÔNG NGHIỆP HIẾU NHUNG', NULL, '965088085', '300 PHỐ HUẾ'),
  ('HLC', 'Công ty cổ phàn HLC Việt Nam', 'Nguyễn Mi Pha', '392667699', 'Hà Nội'),
  ('HN', 'Kho Miêu Nha', NULL, NULL, 'Miêu Nha'),
  ('HOANGMINH', 'CÔNG TY TNHH KDTB MÁY VĂN PHÒNG HOÀNG MINH', 'MS DƯƠNG', '986498500', '121 PHỐ HÀNG BẠC, P HÀNG BẠC, Q HOÀN KIẾM, HÀ NỘI'),
  ('HOAVIET', 'Công ty TNHH thương mại hoá chất và thiết bị Hoa Việt', NULL, '975157569', NULL),
  ('HQ', 'Công ty TNHH giấy và bao bì HQ Việt Nam', 'HQ Việt Nam', '976985104', '976985104'),
  ('HUNGPHAT', 'Công ty tnhh xuất nhập khẩu và công nghệ Hưng Phát', 'Ms Linh', '976074226', 'Số 535 phố Minh Khai, P Vĩnh Tuy, Q Hai Bà Trưng, TP Hà Nội'),
  ('HUONGDUCPHAT', 'Công ty TNHH đầu tư thương mại dịch vụ Hương Đức Phát', '2466507256', NULL, NULL),
  ('KAIZEN', 'KAIZEN', NULL, NULL, 'Công ty Kaizen Hi-tech Việt Nam'),
  ('KEDIDA', 'Shenzhen Kedida', 'Shenzhen Kedida', 'Shenzhen Kedida', 'Shenzhen Kedida'),
  ('KINHVIET', 'CÔNG TY CP KINH VIỆT', 'Ms Hằng', '913590655', 'Thanh Xuân, HN'),
  ('KL', 'Tổng kho thùng Carton giá rẻ K&L', '969225626', NULL, NULL),
  ('KME', 'KME Electronics', 'Ms Phương Anh', '868855536', 'Số 124 ngõ 2 PHạm Văn Đồng, P Mai Dịch, Q Cầu Giấy, Hà n ội'),
  ('KOKEN', 'Công ty TNHH Koken Việt Nam', 'mr', '912367066', 'Trần Bình, Mai Dịch, Cầu Giấy, HN'),
  ('LEBUI', 'Xưởng bao bì Carton Lê Bùi', 'arton Lê Bùi', '988236489', NULL),
  ('LIFE', 'BIONTECH LIFE CO.,LTD', 'BIONTECH LIF', '0989927273', '0989927273'),
  ('LINKI', 'CÔNG TY TNHH LINKI VIỆT NAM', 'MR HIẾU', '986852215', 'LONG BIÊN, HN'),
  ('LOCQT', 'CÔNG TY CÔNG NGHỆ LỌC QUỐC TẾ', NULL, NULL, NULL),
  ('LONGVAN', 'CÔNG TY CỔ PHẦN GIẢI PHÁP HỆ THỐNG LONG VÂN', 'ỐNG LONG VÂN', '0989927274', '0989927274'),
  ('LU WENQI', 'LU WENQI', NULL, NULL, NULL),
  ('MINHLIEN', 'Cửa hàng điện máy Minh Liên', NULL, '915508198', 'Đội 7A Dương Liễu, Hoài Đức, HN'),
  ('MINHQUAN', 'Lọc nước Minh Quân', NULL, NULL, NULL),
  ('MINHSON', 'Côgn ty CP đầu tư công nghệ nghệ Minh Sơn', 'Nguyễn Thị Bích Ngọc', '936373629', 'Số 21 ngách 164 ngõ 192 Lê Trọng Tấn, Định Công, Hoàng Mai, HN'),
  ('MINHTHU', 'Công ty TNHH một thành viên SX, DV và TM Minh Thư', 'Ms Dương', '2432282070', 'Văn Khê, Mê Linh, HN'),
  ('NAMHAI', 'CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI VÀ XNK NAM HẢI', '966165888', NULL, NULL),
  ('NAMVIET', 'Công ty TNHH đầu tư thương mại và Truyền thông Nam Việt', 'Mr Việt', '988113591', 'Đại Mỗ, Nam Từ Liêm, HN'),
  ('NCC00006', 'Cung cấp thùng cacton', 'thùng cacton', '0989927275', '0989927275'),
  ('NCC00008', 'Cửa hàng Thành Hương', 'Thành Hương', '0983799683', '0983799683'),
  ('NCC00043', 'CÔNG TY CỔ PHẦN MAYUWELL CUỘC SỐNG NIỀM TIN', 'ỐNG NIỀM TIN', '0989927277', '0989927277'),
  ('NCC00054', 'CÔNG TY CỔ PHẦN THIẾT BỊ VÀ CÔNG NGHỆ TEKCOM', 'NGHỆ TEKCOM', '0989927278', '0989927278'),
  ('NCCHOANGANH', 'Công ty Hoàng Anh', 'ty Hoàng Anh', '0989927279', '0989927279'),
  ('NCCKHIEMTON', 'NCC NGUYỄN KHIÊM TỐN', 'ỄN KHIÊM TỐN', '0989927280', '0989927280'),
  ('NEWTECH', 'Korea new tech', NULL, NULL, NULL),
  ('Next filter', 'Next filter', NULL, NULL, NULL),
  ('NTTL', 'CÔNG TY TNHH NIỀM TIN THĂNG LONG', 'N THĂNG LONG', '0989927281', '0989927281'),
  ('NUOCNGOAI', 'Nước ngoài', '123', '123', '123'),
  ('PAF', 'Công ty TNHH Thương Mại và Dịch vụ PAF', 'Dịch vụ PAF', '0989927282', '0989927282'),
  ('PCCC', 'Công ty tnhh phòng cháy và cứu nạn cứu hộ Việt Nam', NULL, NULL, NULL),
  ('PHAPVU', 'Vật tư ngành gỗ Pháp Vũ', 'Vũ Đình Pháp', '098****116', 'P Hòa Bình'),
  ('PHATLOC', 'Công ty TNHH vật liệu nhựa Phát Lộc', '(+84)243562415', NULL, NULL),
  ('PHATTHANH', 'Công ty TNHH sản xuất và công nghiệp Phát Thành', 'Ms Thảo', '941830886', 'Số 25, ngõ 122, đường Phú Diễn, P Phú Diễn, quận Bắc Từ Liêm, HN'),
  ('PHONGVIET', 'Công ty TNHHMTV công nghiệp Phong Việt', 'Mr Phong', '936624368', 'LK3-14 Khu đô thị mới Phú Lương, Phú La, Hà Đông'),
  ('PHUCNGUYEN', 'Công ty tnhh TM &SX Phúc Nguyên', 'Hoàng Văn Lương', '965651100', '1155 Nguyễn Văn Linh, P Dị Sử, T Mỹ Hào, Hưng Yên, Việt Nam'),
  ('PRIMER', 'CÔNG TY PRIMER', 'NG TY PRIMER', NULL, NULL),
  ('QUANGTUYEN', 'Công ty TNHH TM điện máy Quang Tuyến', 'Ms Miền', '987686874', '271 Trường TRinh, Thanh Xuân, Hà Nội'),
  ('QUYENHUONG', 'NCC QUYÊN HƯỜNG', 'QUYÊN HƯỜNG', '0989927283', '0989927283'),
  ('ROYAL', 'CÔNG TY CỔ PHẦN IN VÀ TRUYỀN THÔNG ROYAL VIỆT NAM', 'YAL VIỆT NAM', '0989927284', '0989927284'),
  ('SACMAUVIET', 'CÔNG TY TNHH ĐTPT VÀ TM SẮC MÀU VIỆT', 'CTY SẮC MÀU VIỆT', '987156633', 'SỐ 20 NGÕ 80, PHÚ VIÊN, BỒ ĐỀ, LONG BIÊN'),
  ('SAFI', 'Công ty CP bảo hộ lao động Safi', NULL, NULL, NULL),
  ('SD', 'Công ty TNHH thương mại và dịch vụ SD', 'Trần Thị Hồng', '866894099', 'Số 6 khu B TT trung đoàn 664 Vĩnh Quỳnh, Thanh Trì, HN'),
  ('SHENZHEN', 'SHENZHEN', NULL, NULL, NULL),
  ('SHOPPEE', 'Shoppee', 'Hà', '392581335', 'shoppee'),
  ('SHOPTHO', 'SHOPTHO', '0912183983', NULL, NULL),
  ('SON HA', 'Sơn Hà', 'Ms Hà', '392581335', 'Minh Khai Bắc Từ Liêm Hà Nội'),
  ('SONGHONGVIET', 'Công ty TNHH Sông Hồng Việt', 'MS Hà', '392581335', 'Cụm công nghiệp Liên Phượng, Thường Tín, Hà Nội'),
  ('SONHA', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN SƠN HÀ', 'ĐOÀN SƠN HÀ', '0989927270', '0989927270'),
  ('SYPHUONG', 'Cửa hàng đồ điện dân dụng Sỹ Phượng', 'Mr Sỹ', '339613817', 'đường 70 Phú Thứ, ây Mỗ, Nam Từ Liêm, HN'),
  ('TANHUNGTHANH', 'Công ty CP SXTM&dịch vụ Tân Hưng Thành', 'Mr Hồng', '978838313', 'Đội 7B Dương Liễu, Hòai Đức, HN'),
  ('TANTHANHCHUNG', 'Công ty TNHH sản xuất &thương mại Tân Thành Chung', 'Mr Chung', '392581335', 'Ngọc Thụy, Long Biên, Hà Nội'),
  ('TANTRUONGGIANG', 'Công ty CP đầu tư và phát triển thương mại Tân Trường Giang', NULL, NULL, NULL),
  ('TATICO', 'Công ty CP Tatico Việt Nam', 'ico Việt Nam', NULL, NULL),
  ('TAYAN', 'Công ty TNHH đầu tư và thương mại Tây An', 'Ms Thủy', '375504891', 'Số 85 đường 70 Miêu Nha, Tây Mỗ'),
  ('TECOMEN', 'Công ty TNHH Công nghệ Tecomen', 'Mr Hưng', '392581335', 'Yên Phú, Yên Mỹ, Hưng Yên'),
  ('THANH HUONG', 'Cửa hàng Thành Hương', 'C Hương', '983799683', 'Miêu Nha, Tây Mỗ, Nam Từ Liêm, HN'),
  ('THANH THAI', 'Công Ty TNHH Thương Mại Thành Thái', 'Chu Kim Anh', '902282337', 'Hà Nội'),
  ('THIENSON', 'Công ty CP công nghệ môi trường Thiên Sơn', 'Công ty CP công nghệ môi trường Thiên Sơn', '392581335', 'Thôn Đông KHê, xã Đan Phượng, huyện ĐAn Phượng, Hà Nội'),
  ('THINHTHANH', 'Công ty TNHH vật tư xây lắp Thịnh Thành', NULL, NULL, 'Tầng 6 tòa nhà Việt Á, số 9 Duy Tân, dịch Vọng Hậu, Cầu Giấy, Hà Nội'),
  ('THUANLOI', 'Công ty TNHH xe nâng Thuận Lợi', 'Mr Lợi', '976890168', 'Đức Giang, Long Biên, Hà Nội'),
  ('TIENDAT', 'CÔNG TY TIẾN ĐẠT', 'TY TIẾN ĐẠT', NULL, NULL),
  ('TMINSPIRE', 'CÔNG TY TNHH TRUYỀN THÔNG VÀ THƯƠNG MẠI INSPIRE', 'MẠI INSPIRE', '0989927285', '0989927285'),
  ('TOANTHANG', 'Đại lý Toàn Thắng', 'Ngô Văn Thắng', '0962444955-0343966108', 'khu 3 đất dịch vụ An Thọ An Khánh, Hoài Đức, HN'),
  ('TOANTHUY', 'Vật tư cơ khí Toản Thủy', 'Mr Cương', '936323536', '437 Đại Mỗ, Nam Từ Liêm, HN'),
  ('TPP', 'Công ty TNHH TPP Việt Nam', 'Phươqng', '392581335', 'Hà Đông, Hà Nội'),
  ('TRANG', 'Cửa hàng Trang', 'a hàng Trang', '947990941', '947990941'),
  ('TRANHUNG', 'Máy lọc nước Trần Hùng', 'ớc Trần Hùng', '969462146', NULL),
  ('TRUNGTHAI', 'CÔNG TY TNHH MTV TRUNG THÁI HÀ NỘI', '912174141', NULL, NULL),
  ('TRUONGSON', 'Công ty TNHH thươg mại và xây dựng Trường Sơn', NULL, '912760041', 'Đội 4, xã Chàng Sơn, huyện Thạch Thất, TP Hà Nội'),
  ('TUAN', 'Nguyễn Văn Tuấn', 'Nguyễn Văn Tuấn', '899579998', 'Dương Nội, Hà Đông'),
  ('VANPHUBINH', 'VẠN PHÚ BÌNH', NULL, '2838774250', 'CCN ĐỨC HÒA HẠ, xã Đức Hoà, huyện Đức Hoà, Long An'),
  ('VANTHANH', 'Y TẾ VẠN THÀNH', 'MR THÀNH', '906719620', 'P11,Q10, HCM'),
  ('VANXUAN', 'Vạn Xuân', NULL, '944999025', NULL),
  ('VIETBOX', 'Bao bì Tân Thành Đạt', '944130188', NULL, NULL),
  ('VINHYEN', 'VINHYEN', 'Cô Yên', '976129915', 'Cát Quế, Hoài Đức, Hà Nội'),
  ('VTP', 'Viettel Post', NULL, NULL, NULL),
  ('WACO', 'WACO CORP', NULL, NULL, NULL),
  ('WELLSYS', 'Công ty LD SX điện gia dụng Wellsys', NULL, NULL, NULL),
  ('WINLINE', 'CÔNG TY TNHH WINLINE VIỆT NAM', 'INE VIỆT NAM', '02436830375-0963230665', NULL),
  ('Wonbong', 'Wonbong', 'Ms Hà', '392581335', 'Hàn Quốc'),
  ('WORLWELL', 'Công ty Cp Công nghệ và môi trường Worlwell', NULL, NULL, NULL),
  ('XEKHUONG1', 'CÔNG TY TNHH GIẢI PHÁP KẾT NỐI', 'PHÁP KẾT NỐI', '0989927286', '0989927286'),
  ('XOP', 'Xốp bọc Phú Diễn', 'MS Hương', '972209122', 'Phú Diễn')
ON CONFLICT (ma_ncc) DO NOTHING;
